apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapp-backend
  template:
    metadata:
      labels:
        app: weatherapp-backend
    spec:
      containers:
        - name: weatherapp-backend
          image: "205337945058.dkr.ecr.eu-north-1.amazonaws.com/omerapp99/weather:latest"
          ports:
            - containerPort: 5000  # The backend runs on port 5000
          resources:
            requests:
              memory: "150Mi"
              cpu: "150m"
            limits:
              memory: "300Mi"
              cpu: "300m"
