apiVersion: v1
kind: Service
metadata:
  name: weatherapp-backend-service
spec:
  selector:
    app: weatherapp-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
